# Generated by Django 5.0 on 2023-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('select_hotel', models.CharField(choices=[('hotel1', 'Hotel 1'), ('hotel2', 'Hotel 2'), ('hotel3', 'Hotel 3')], max_length=255)),
                ('packages_inclusion', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
