# Generated by Django 5.0 on 2023-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='select_hotel',
            field=models.CharField(choices=[('5star', '5Star'), ('4star', '4Star'), ('3star', '3Star')], max_length=255),
        ),
    ]
