# Generated by Django 4.2.8 on 2023-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_alter_travelpackage_select_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('passport', models.FileField(blank=True, null=True, upload_to='image/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='image/')),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='select_hotel',
            field=models.CharField(choices=[('5star', '5 Star'), ('4star', '4 Star'), ('3star', '3 Star')], max_length=255),
        ),
    ]
