# Generated by Django 4.1.13 on 2024-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_feedback_travelpackage_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image1', models.FileField(blank=True, null=True, upload_to='image/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='image/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='image/')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
